const { ctx, sheets, cacheStore } = require('./gas-mock');
const api = (a, p) => ctx.api(a, p);
const log = (t, v) => console.log(t.padEnd(38), JSON.stringify(v).slice(0, 200));
ctx.setup();
log('ping light', api('ping', { light: '1' }));
const base = { reporter: 'A', job: 'V-100', date: '2026-10-09', shift: 'Day', op_mgr: '1', arr_bee: '07:00' };
log('submit no location', api('submit', { ...base, sid: 's1' }));
log('submit new job+loc', api('submit', { ...base, sid: 's2', location: 'โรงงาน C' }));
log('submit same sid again', api('submit', { ...base, sid: 's2', location: 'โรงงาน C' }));
log('submit same job other case', api('submit', { ...base, sid: 's3', job: 'v100', location: ' โรงงาน  c ' }));
for (const k in cacheStore) if (k.startsWith('sid:')) delete cacheStore[k];
log('resubmit s2 after cache expiry', api('submit', { ...base, sid: 's2', location: 'โรงงาน C' }));
log('Records rows', sheets.Records.getLastRow() - 1);
log('Jobs tab', sheets.Jobs.data.slice(1).map(r => r[0]));
log('Locations tab', sheets.Locations.data.slice(1).map(r => r[0]));
const r1 = api('getReport', { paged: '1', limit: '50' });
log('getReport', { n: r1.rows.length, ver: r1.ver });
log('getReport same ver', api('getReport', { paged: '1', limit: '50', ver: r1.ver }));
api('submit', { ...base, sid: 's9', location: 'X' });
log('getReport after write', (x => ({ unchanged: x.unchanged, n: x.rows && x.rows.length }))(api('getReport', { paged: '1', limit: '50', ver: r1.ver })));
log('update without PIN (open mode)', api('update', { sid: 's2', location: '', job: 'V-100' }));
log('update new location', api('update', { sid: 's2', location: 'Site Z', reporter: 'A', job: 'V-100', date: '2026-10-09', shift: 'Day' }));
log('Locations after update', sheets.Locations.data.slice(1).map(r => r[0]));
log('getConfig sections', (c => [c.config.sections_location, c.config.require_location])(api('getConfig', {})));
ctx.__props.ADMIN_PINS = 'Boss:1234:admin';
log('delete no pin', api('delete', { sid: 's2' }));
log('delete wrong pin', api('delete', { sid: 's2', pin: '9', dev: 'd' }));
log('delete ok', api('delete', { sid: 's2', pin: '1234', dev: 'd' }));
log('bulkImport (no auth!)', api('bulkImport', { data: JSON.stringify([['B', 'J-9', '2026-10-01', 'Night']]) }));
log('LINE register w/o code', (() => { let r; ctx.lineReply_ = (t, m) => r = m; ctx.handleLineWebhook({ events: [{ type: 'message', message: { type: 'text', text: 'ลงทะเบียน' }, replyToken: 't', source: { groupId: 'evil' } }] }); return [r, ctx.__props.LINE_TARGET_ID || null]; })());
log('ErrorLog rows', sheets.ErrorLog ? sheets.ErrorLog.getLastRow() - 1 : 0);
